// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vfp32_multiplier.h for the primary calling header

#include "Vfp32_multiplier__pch.h"
#include "Vfp32_multiplier__Syms.h"
#include "Vfp32_multiplier___024root.h"

#ifdef VL_DEBUG
VL_ATTR_COLD void Vfp32_multiplier___024root___dump_triggers__stl(Vfp32_multiplier___024root* vlSelf);
#endif  // VL_DEBUG

VL_ATTR_COLD void Vfp32_multiplier___024root___eval_triggers__stl(Vfp32_multiplier___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vfp32_multiplier___024root___eval_triggers__stl\n"); );
    Vfp32_multiplier__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.__VstlTriggered.setBit(0U, (IData)(vlSelfRef.__VstlFirstIteration));
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vfp32_multiplier___024root___dump_triggers__stl(vlSelf);
    }
#endif
}

void Vfp32_multiplier___024root___ico_sequent__TOP__0(Vfp32_multiplier___024root* vlSelf);
VL_ATTR_COLD void Vfp32_multiplier___024root____Vm_traceActivitySetAll(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__1__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__1(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__2__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__3__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__2(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__4__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__5__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__3(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__6__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__7__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__4(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__8__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__9__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__5(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__10__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__11__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__6(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__12__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__13__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__7(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__14__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__15__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__8(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__16__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__17__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__9(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__18__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__19__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__10(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__20__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__21__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__11(Vfp32_multiplier___024root* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__22__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__23__KET____DOT__u_adder__0(Vfp32_multiplier_adder_nbit__W30* vlSelf);
void Vfp32_multiplier___024root___ico_sequent__TOP__12(Vfp32_multiplier___024root* vlSelf);

VL_ATTR_COLD void Vfp32_multiplier___024root___eval_stl(Vfp32_multiplier___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vfp32_multiplier___024root___eval_stl\n"); );
    Vfp32_multiplier__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    if ((1ULL & vlSelfRef.__VstlTriggered.word(0U))) {
        Vfp32_multiplier___024root___ico_sequent__TOP__0(vlSelf);
        Vfp32_multiplier___024root____Vm_traceActivitySetAll(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__1__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__1__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__1(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__2__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__2__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__3__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__3__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__2(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__4__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__4__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__5__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__5__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__3(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__6__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__6__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__7__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__7__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__4(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__8__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__8__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__9__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__9__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__5(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__10__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__10__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__11__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__11__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__6(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__12__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__12__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__13__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__13__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__7(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__14__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__14__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__15__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__15__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__8(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__16__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__16__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__17__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__17__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__9(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__18__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__18__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__19__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__19__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__10(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__20__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__20__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__21__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__21__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__11(vlSelf);
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__22__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__22__KET____DOT__u_adder));
        Vfp32_multiplier_adder_nbit__W30___ico_sequent__TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__23__KET____DOT__u_adder__0((&vlSymsp->TOP__fp32_multiplier__DOT__u_multiplier__DOT__multiplier_chain__BRA__23__KET____DOT__u_adder));
        Vfp32_multiplier___024root___ico_sequent__TOP__12(vlSelf);
    }
}
